<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ListTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table( 'list')->insert([
            [
                'recruitment year' => 2020,
                'application start date' => '2020-08-07',
                'application deadline' => '2023-12-31',
                'project name' => '2021-2023臺美GEMT雙邊協議合作研究計畫',
                'country' => '美國',
                'agreement agency' => '美國國家科學基金會(NSF)',
            ],
            [
                'recruitment year' => 2021,
                'application start date' => '2021-01-01',
                'application deadline' => '2027-12-31',
                'project name' => '2021-2027徵求成功參與歐盟跨國團隊科研暨創新計畫',
                'country' => '歐盟',
                'agreement agency' => '歐盟',
            ],
            [
                'recruitment year' => 2022,
                'application start date' => '2022-09-29',
                'application deadline' => '2023-01-17',
                'project name' => '臺美(NSTC-NSF)先進半導體晶片設計及製作(ACED Fab)合作計畫',
                'country' => '美國',
                'agreement agency' => '美國國家科學基金會(NSF)',
            ],
            [
                'recruitment_year' => 2022,
                'application_start_date' => '2022-10-03',
                'application_deadline' => '2023-03-23',
                'project_name' => '2024臺法(NSTC-INCa)雙邊協議擴充加值(add-on)國際合作研究計畫',
                'country' => '法國',
                'agreement_agency' => '法國國家癌症研究院(INCa)',
            ],
            [
                'recruitment_year' => 2022,
                'application_start_date' => '2022-10-20',
                'application_deadline' => '2023-01-03',
                'project_name' => '2023年臺愛(NSTC-ETAg)雙邊合作人員交流互訪計畫',
                'country' => '愛沙尼亞',
                'agreement_agency' => '愛沙尼亞研究委員會(ETAG)',
            ],
            [
                'recruitment_year' => 2022,
                'application_start_date' => '2022-11-03',
                'application_deadline' => '2023-02-02',
                'project_name' => '國科會同步徵求2022年歐盟「未來新興信息與通訊技術研究(CHIST-ERA)」跨國多邊合作計畫',
                'country' => '歐盟',
                'agreement_agency' => '歐盟',
            ],
            [
                'recruitment_year' => 2022,
                'application_start_date' => '2022-11-15',
                'application_deadline' => '2023-02-07',
                'project_name' => '臺英(NSTC-ESRC)雙邊人員交流計畫',
                'country' => '英國',
                'agreement_agency' => '英國經濟暨社會研究委員會',
            ],
            [
                'recruitment_year' => 2022,
                'application_start_date' => '2022-11-15',
                'application_deadline' => '2023-02-15',
                'project_name' => '2023-2026臺德(NSTC-DFG)雙邊協議國際合作研究計畫(3年期)',
                'country' => '德國',
                'agreement_agency' => '德國國家研究基金會(DFG)',
            ],
            [
                'recruitment_year' => 2022,
                'application_start_date' => '2022-12-09',
                'application_deadline' => '2023-02-07',
                'project_name' => '國科會同步徵求2022年歐盟促進歐洲健康研究領夥伴關係(ERA4health)之聯合跨國多邊「CARDINNOV」合作計畫',
                'country' => '歐盟',
                'agreement_agency' => '歐盟',
            ],
            [
                'recruitment_year' => 2022,
                'application_start_date' => '2022-12-28',
                'application_deadline' => '2023-03-07',
                'project_name' => '國科會同步徵求2023年歐盟ERA-NET NEURON聯合跨國多邊「心理健康中環境挑戰的恢復力和脆弱性機制研究」計畫',
                'country' => '歐盟',
                'agreement_agency' => '歐盟',
            ],
            [
                'recruitment_year' => 2022,
                'application_start_date' => '2022-12-28',
                'application_deadline' => '2023-03-14',
                'project_name' => '國科會同步徵求2023年歐盟促進歐洲健康研究領夥伴關係(ERA4Health Partnership)之聯合跨國多邊「HealthEquity」合作計畫',
                'country' => '歐盟',
                'agreement_agency' => '歐盟',
            ],
            [
                'recruitment_year' => 2022,
                'application_start_date' => '2022-12-28',
                'application_deadline' => '2023-05-04',
                'project_name' => '國科會同步徵求2023年歐盟ERA-NET NEURON聯合跨國多邊「神經科學的倫理、法律和社會層面探討 (ELSA)」計畫',
                'country' => '歐盟',
                'agreement_agency' => '歐盟',
            ],
            [
                'recruitment_year' => 2022,
                'application_start_date' => '2022-12-29',
                'application_deadline' => '2023-04-27',
                'project_name' => '臺以(NSTC-MIST)雙邊合作研究計畫',
                'country' => '以色列',
                'agreement_agency' => '以色列科技部',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-01-03',
                'application_deadline' => '2023-02-24',
                'project_name' => '臺西(NSTC-CSIC)博士生研習計畫',
                'country' => '西班牙',
                'agreement_agency' => '西班牙國家高等科學研究委員會(CSIC)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-01-12',
                'application_deadline' => '2023-02-15',
                'project_name' => '2023年臺德(DAAD)暑期營',
                'country' => '德國',
                'agreement_agency' => '德國學術交流總署(DAAD)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-01-16',
                'application_deadline' => '2023-04-17',
                'project_name' => '臺日(NSTC-RIKEN)雙邊合作研究計畫',
                'country' => '日本',
                'agreement_agency' => '日本國立研究開發法人理化學研究所(RIKEN)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-01-16',
                'application_deadline' => '2023-03-30',
                'project_name' => '臺英(NSTC-NERC)雙邊合作研究計畫(環境科學領域)',
                'country' => '英國',
                'agreement_agency' => '英國自然環境研究委員會(NERC)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-01-16',
                'application_deadline' => '2023-04-28',
                'project_name' => '臺蒙(NSTC-MECSS/MFST)雙邊合作研究計畫',
                'country' => '蒙古',
                'agreement_agency' => '蒙古教育文化科學體育(MECSS)及蒙古科學技術基金會(MFST)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-01-16',
                'application_deadline' => '2023-05-15',
                'project_name' => '臺菲(NSTC-DOST)雙邊協議國際合作研究計畫(第二階段)',
                'country' => '菲律賓',
                'agreement_agency' => '菲律賓科技部(DOST)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-02-10',
                'application_deadline' => '2023-03-31',
                'project_name' => '臺法(NSTC-ANR)國際合作研究計畫',
                'country' => '法國',
                'agreement_agency' => '法國國家研究總署(ANR)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-02-13',
                'application_deadline' => '2023-05-02',
                'project_name' => '臺拉立三邊協議國際合作研究計畫',
                'country' => '拉脫維亞及立陶宛',
                'agreement_agency' => '拉脫維亞、立陶宛教育及科學部',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-02-13',
                'application_deadline' => '2023-04-06',
                'project_name' => '臺捷(NSTC-GACR)雙邊合作研究計畫',
                'country' => '捷克',
                'agreement_agency' => '捷克科學基金會(GACR)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-02-24',
                'application_deadline' => '2023-03-24',
                'project_name' => '2023年國際共同研究暨培訓型合作活動計畫',
                'country' => '東南亞、南亞、中東、大洋洲、中南美洲等區域發展中國家',
                'agreement_agency' => '-',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-03-01',
                'application_deadline' => '2023-05-01',
                'project_name' => '臺印(NSTC-ICSSR)社會科學雙邊協議國際合作研究計畫',
                'country' => '印度',
                'agreement_agency' => '印度教育部社會科學研究委員會(ICSSR)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-03-07',
                'application_deadline' => '2023-05-16',
                'project_name' => '國科會同步徵求2023年歐盟「材料與電池技術研究暨創新計畫(M-ERA.NET 3)」跨國多邊合作計畫',
                'country' => '歐盟',
                'agreement_agency' => '歐盟',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-03-07',
                'application_deadline' => '2023-06-01',
                'project_name' => '國科會同步徵求2023年歐盟「歐洲研究領域網絡旗艦計畫(FLAG-ERA)」跨國多邊合作計畫',
                'country' => '歐盟',
                'agreement_agency' => '歐盟',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-03-10',
                'application_deadline' => '2023-07-14',
                'project_name' => '臺法雙邊人員交流互訪型計畫(幽蘭計畫)',
                'country' => '法國',
                'agreement_agency' => '法國在台協會(BFT)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-03-10',
                'application_deadline' => '2023-07-14',
                'project_name' => '臺法雙邊研討會(幽蘭計畫)',
                'country' => '法國',
                'agreement_agency' => '法國在台協會(BFT)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-03-31',
                'application_deadline' => '2023-06-19',
                'project_name' => '2023年臺法科技獎(The France-Taiwan Scientific Grand Prize)',
                'country' => '法國',
                'agreement_agency' => '法蘭西學院自然科學院(ADS)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-03-31',
                'application_deadline' => '2023-07-31',
                'project_name' => '2024-2027臺日(NSTC-JST)雙邊合作研究計畫',
                'country' => '日本',
                'agreement_agency' => '日本國立研究開發法人科學技術振興機構(JST)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-04-01',
                'application_deadline' => '2023-06-12',
                'project_name' => '臺捷(NSTC-CAS)雙邊計畫人員交流PPP計畫',
                'country' => '捷克',
                'agreement_agency' => '捷克科學院(CAS)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-04-03',
                'application_deadline' => '2023-05-26',
                'project_name' => '臺斯(NSTC-SAS)雙邊合作研究計畫',
                'country' => '斯洛伐克',
                'agreement_agency' => '斯洛伐克科學院(SAS)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-04-03',
                'application_deadline' => '2023-07-31',
                'project_name' => '臺波(NSTC-PAS)雙邊計畫人員交流PPP計畫',
                'country' => '波蘭',
                'agreement_agency' => '波蘭科學院(PAS)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-04-03',
                'application_deadline' => '2023-06-16',
                'project_name' => '2024-2025臺韓(NSTC-NRF)雙邊合作研究計畫',
                'country' => '韓國',
                'agreement_agency' => '韓國國家研究基金會(NRF)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-04-05',
                'application_deadline' => '2023-06-21',
                'project_name' => '臺德(NSTC-DAAD)雙邊計畫人員交流PPP計畫',
                'country' => '德國',
                'agreement_agency' => '德國學術交流總署(DAAD)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-04-11',
                'application_deadline' => '2023-06-19',
                'project_name' => '臺波(NSTC-NCBR)雙邊合作研究計畫及國際合作鏈結法人計畫',
                'country' => '波蘭',
                'agreement_agency' => '波蘭國家研究發展中心(NCBR)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-05-04',
                'application_deadline' => '2023-07-31',
                'project_name' => '臺保(NSTC-BAS)雙邊計畫人員交流PPP計畫',
                'country' => '保加利亞',
                'agreement_agency' => '保加利亞科學院(BAS)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-05-09',
                'application_deadline' => '2023-07-21',
                'project_name' => '國科會同步徵求2023年歐盟「癌症轉譯(TRANSCAN-3)」聯合跨國多邊合作計畫',
                'country' => '歐盟',
                'agreement_agency' => '歐盟',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-05-18',
                'application_deadline' => '2023-07-19',
                'project_name' => '臺捷(NSTC-TACR)雙邊協議國際合作鏈結法人計畫',
                'country' => '捷克',
                'agreement_agency' => '捷克技術署(TACR)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-05-29',
                'application_deadline' => '2023-09-18',
                'project_name' => '臺匈(NSTC-HAS)雙邊計畫人員交流PPP計畫',
                'country' => '匈牙利',
                'agreement_agency' => '匈牙利科學院(HAS)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-06-01',
                'application_deadline' => '2023-07-31',
                'project_name' => '臺印(NSTC-DST)雙邊協議國際合作研究計畫',
                'country' => '印度',
                'agreement_agency' => '印度科技部(DST)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-06-05',
                'application_deadline' => '2023-07-28',
                'project_name' => '臺法(NSTC-INSERM)雙邊人員交流計畫',
                'country' => '法國',
                'agreement_agency' => '法國國家健康與醫學研究院(INSERM)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-06-12',
                'application_deadline' => '2023-07-31',
                'project_name' => '臺日青年科技人才交流計畫(日本臺灣交流協會訪日研究活動)─選送博士生赴日研究',
                'country' => '日本',
                'agreement_agency' => '日本台灣交流協會',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-06-12',
                'application_deadline' => '2023-09-15',
                'project_name' => '臺西(NSTC-CSIC)雙邊人員交流計畫',
                'country' => '西班牙',
                'agreement_agency' => '西班牙國家高等科學研究委員會(CSIC)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-07-06',
                'application_deadline' => '2023-09-28',
                'project_name' => '臺法(NSTC-CNRS)國際新興活動(IEA)雙邊人員交流計畫',
                'country' => '法國',
                'agreement_agency' => '法國國家科學研究院(CNRS)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-07-12',
                'application_deadline' => '2023-09-05',
                'project_name' => '臺德(NSTC-BMBF)半導體晶片設計學術合作研究計畫(試辦方案)(構想書)',
                'country' => '德國',
                'agreement_agency' => '德國聯邦教育及研究部(BMBF)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-08-02',
                'application_deadline' => '2023-09-27',
                'project_name' => '臺英(NSTC-RS)雙邊合作人員交流計畫(自然科學領域, Cost Share Programme, CSP)',
                'country' => '英國',
                'agreement_agency' => '英國皇家學會(RS)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-08-04',
                'application_deadline' => '2023-10-02',
                'project_name' => '2024年歐盟大型儀器培訓計畫(HERCULES)',
                'country' => '法國',
                'agreement_agency' => '法國格列諾柏大學(協辦)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-08-23',
                'application_deadline' => '2023-09-20',
                'project_name' => '臺芬(NSTC-AKA)雙邊合作人員交流計畫',
                'country' => '芬蘭',
                'agreement_agency' => '芬蘭科學院(AKA)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-09-06',
                'application_deadline' => '2023-11-08',
                'project_name' => '臺英(NSTC-BA)雙邊小型研究計畫(人文領域, Small Research Grant, SRG)',
                'country' => '英國',
                'agreement_agency' => '英國國家學術院(BA)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-09-07',
                'application_deadline' => '2023-10-26',
                'project_name' => '臺英(NSTC-RSE)雙邊訪問計畫(不限領域, Bilateral Visits Programme, BVP)',
                'country' => '英國',
                'agreement_agency' => '英國愛丁堡皇家學會(RSE)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-09-11',
                'application_deadline' => '2023-11-10',
                'project_name' => '國科會同步徵求2023年歐盟「生物多樣性(Biodiversa+: European Biodiversity Partnership)」跨國多邊合作計畫pre-proposals',
                'country' => '歐盟',
                'agreement_agency' => '歐盟',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-09-14',
                'application_deadline' => '2023-10-19',
                'project_name' => '2024臺法(NSTC-ANR)雙邊協議國際合作研究計畫',
                'country' => '法國',
                'agreement_agency' => '法國國家研究總署(ANR)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-11-01',
                'application_deadline' => '2024-02-01',
                'project_name' => '2025-2027臺灣-德國(NSTC-DFG)雙邊協議專案型國際合作研究計畫',
                'country' => '德國',
                'agreement_agency' => '德國國家研究基金會(DFG)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-11-03',
                'application_deadline' => '2024-01-15',
                'project_name' => '國科會同步徵求2024年歐盟促進歐洲健康研究領夥伴關係(ERA4Health Partnership)之聯合跨國多邊「NutriBrain」合作計畫',
                'country' => '歐盟',
                'agreement_agency' => '歐盟',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-11-14',
                'application_deadline' => '2024-01-30',
                'project_name' => '國科會同步徵求2024年歐盟促進歐洲健康研究領夥伴關係(ERA4Health Partnership)之聯合跨國多邊「NANOTECMEC」合作計畫',
                'country' => '歐盟',
                'agreement_agency' => '歐盟',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-11-15',
                'application_deadline' => '2024-01-15',
                'project_name' => '2024年臺愛(NSTC-ETAg)雙邊合作人員交流互訪計畫',
                'country' => '愛沙尼亞',
                'agreement_agency' => '愛沙尼亞研究委員會(ETAG)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-12-08',
                'application_deadline' => '2024-02-21',
                'project_name' => '2024年度臺日青年科技人才交流計畫',
                'country' => '日本',
                'agreement_agency' => '日本台灣交流協會',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-12-18',
                'application_deadline' => '2024-03-20',
                'project_name' => '2024年臺德(NSTC-DAAD)青年暑期營',
                'country' => '德國',
                'agreement_agency' => '德國學術交流總署(DAAD)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '2023-12-18',
                'application_deadline' => '2024-02-22',
                'project_name' => '2025年度臺灣與菲律賓(NSTC-DOST)雙邊協議國際合作研究計畫(第一階段研究構想書)',
                'country' => '菲律賓',
                'agreement_agency' => '菲律賓科技部(DOST)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '隨到隨審',
                'application_deadline' => '隨到隨審',
                'project_name' => '臺灣-德國(NSTC-DFG)雙邊研討會(隨到隨審, 6個月前提出申請)',
                'country' => '德國',
                'agreement_agency' => '德國國家研究基金會(DFG)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '隨到隨審',
                'application_deadline' => '隨到隨審',
                'project_name' => '臺灣-德國(NSTC-DFG)研究訪問計畫 (隨到隨審, 6個月前提出申請)',
                'country' => '德國',
                'agreement_agency' => '德國國家研究基金會(DFG)',
            ],
            [
                'recruitment_year' => 2023,
                'application_start_date' => '隨到隨審',
                'application_deadline' => '隨到隨審',
                'project_name' => '補助學研機構與德國馬克斯普朗克研究院(MPI)合設 「國際馬克斯普朗克中心 International Max Planck Center」 先導計畫',
                'country' => '德國',
                'agreement_agency' => '',
            ],
            //...依此類推，為每組資料新增陣列
        ]);
        DB::table('oberservation')->insert($articles);
    }
}
